repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        exclude: '\.*conda/.*'
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: '\.txt$|\.tsv$'
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/populationgenomics/pre-commits
    rev: "v0.1.3"
    hooks:
      - id: cpg-id-checker

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --check src/
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check src/
        language: system
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        entry: uv run mypy src/
        language: system
        pass_filenames: false
        always_run: true
