/**
 * Deployment-style entry for `@flowajs/chat-service`.
 *
 * The shape — load env, build a Storage and an LlmProvider via the package's
 * factory exports, import a Zod schema from a prompt-set workspace package,
 * call `createApp({ schema, ... })`, serve with `@hono/node-server` — is the
 * worked example of how to write a custom entry. Production deployments
 * typically differ only in the credential chain used to construct SDK
 * clients before passing them to the programmatic `{ client }` factory
 * variants (`createS3Storage({ client })`, `createBedrockProvider({ client })`,
 * etc.). They do not edit this file.
 */

import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { serve } from "@hono/node-server";
import { createApp } from "@flowajs/chat-service/server";
import { createFsStorage } from "@flowajs/chat-service/storage/fs";
import { createProvider } from "@flowajs/chat-service/llm";
import { ArtifactSchema } from "@flowajs/prompts/generic";

// Load .env if present. Idempotent: when launched by start.ts the env is
// already populated; when run standalone (`pnpm chat-service`) this picks
// up the file. process.loadEnvFile is stable in Node 24.
try {
  process.loadEnvFile(resolve(process.cwd(), ".env"));
} catch {
  // .env is optional.
}

const llmModel = process.env.LLM_MODEL;
if (!llmModel) {
  console.error(
    "LLM_MODEL is not set. Copy examples/demo/.env.example to .env and uncomment one provider block.",
  );
  process.exit(1);
}

const port = Number.parseInt(process.env.CHAT_SERVICE_PORT ?? "7701", 10);
if (!Number.isFinite(port) || port <= 0) {
  console.error(
    `CHAT_SERVICE_PORT must be a positive integer, got: ${process.env.CHAT_SERVICE_PORT}`,
  );
  process.exit(1);
}

const dataRoot = resolve(
  process.cwd(),
  process.env.DEMO_DATA_DIR ?? "./demo-data",
);

// Locate the prompt-template directory by resolving the schema's package
// export — `prompts/generic/aggregate_edit_schema.ts` lives in the same
// directory as `aggregate_edit_prompt.txt`, which is what
// `loadEditPromptTemplate` reads.
const promptDir = dirname(
  fileURLToPath(import.meta.resolve("@flowajs/prompts/generic")),
);

const storage = createFsStorage({ root: dataRoot });
const provider = await createProvider(llmModel);

// Sessions don't survive a chat-service restart in the demo; a per-boot
// random secret is fine. Production deployments inject a stable secret.
const jwtSecret =
  process.env.CHAT_JWT_SECRET ?? randomBytes(32).toString("hex");

const app = createApp({
  storage,
  provider,
  schema: ArtifactSchema,
  jwtSecret,
  promptDir,
});

serve({ fetch: app.fetch, port }, (info) => {
  console.log(
    `chat-service listening on http://localhost:${info.port} (provider: ${provider.name}, dataRoot: ${dataRoot})`,
  );
});

// Keep the process alive even if the import-graph above completes;
// @hono/node-server's serve() registers the listener but does not block.
// (Node keeps the loop alive while the server has an active handle, so
// this is just defensive against future refactors.)
process.on("SIGINT", () => process.exit(0));
process.on("SIGTERM", () => process.exit(0));
